name: bson
version: 0.1.22
authors:
- Vadim Tsushko <vadimtsushko@gmail.com>
- Ad van der Veer <advanderveer@gmail.com>
description: Bson library for Dart programming language. BSON, short for Binary JSON, is a binary-encoded serialization of JSON-like documents.
homepage: https://github.com/vadimtsushko/bson
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  fixnum: '>=0.9.0'
  more: '>=1.3.2 <2.0.0'
dev_dependencies:
  browser: '>=0.9.0 <0.10.0'
  unittest: '>=0.9.0 <0.10.0'
