name: bson
version: 0.1.8
authors:
- Vadim Tsushko <vadimtsushko@gmail.com>
- Ad van der Veer <advanderveer@gmail.com>
description: Bson library for Dart programming language. BSON, short for Binary JSON, is a binary-encoded serialization of JSON-like documents.
homepage: https://github.com/vadimtsushko/bson
dependencies:
  meta: any
dev_dependencies:
  browser: any
  unittest: any
