name: bson
description: Bson library for Dart programming language
version: 0.0.3-dev
author: Vadim Tsushko <vadimtsushko@gmail.com>
homepage: https://github.com/vadimtsushko/bson_dart
dependencies:
  unittest:
    sdk: unittest
