name: bson
version: 4.0.1-1.0.dev

description: Bson library for Dart programming language. BSON, short for Binary JSON, is a binary-encoded serialization of JSON-like documents.
homepage: https://github.com/mongo-dart/bson

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  fixnum: ^1.0.0
  decimal: ^2.3.0
  rational: ^2.2.0
  uuid: ^3.0.0
  packages_extensions: ^0.1.0
  power_extensions: ^0.2.0


dev_dependencies:
  test: ^1.16.4
  lints: ^2.0.0

