name: bson
version: 2.0.2

description: Bson library for Dart programming language. BSON, short for Binary JSON, is a binary-encoded serialization of JSON-like documents.
homepage: https://github.com/mongo-dart/bson

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  fixnum: ^1.0.0
  decimal: '>=2.0.0 <2.3.0'
  rational: ^2.2.0
  uuid: ^3.0.0

dev_dependencies:
  test: ^1.16.4
  lints: ^2.0.0

